### ISSUE TITLE
new `FunctionDefinition` incompatible with azure

### ISSUE THREAD

**Issue by Ran-Mewo** [Lambdua/openai4j#15]
Using the new `FunctionDefinition` returns this on azure's `gpt-4-turbo`
```json
  "error": {
    "message": "1 validation error for Request\nbody -> tools\n  extra fields not permitted (type=value_error.extra)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
```
  
  Looking at the converted JSON (*I used `ObjectMapper().writeValueAsString` so I am not sure if it's accurate*)
  ```json
  {
      "type": "function",
      "function": {
        "name": "wolframAlpha",
        "description": "Computes mathematical expressions using WolframAlpha",
        "parameters": {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "title": "Wolfram Alpha Function",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "input": {
              "type": "string"
            }
          }
        }
      }
    }
```
seems like azure doesn't support the `"$schema"`, `"title"`, `"aditionalProperties"` fields as I can't find these in any documentation

another limitation with the new `FunctionDefinition` is that it doesn't allow parameterless functions, the parameters field is optional and can be omitted
 > [Omitting parameters defines a function with an empty parameter list.](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools)

**Comment by Lambdua** [comment]
Okay, I'll see later

**Comment by Lambdua** [comment]
I don't have an Azure API key. It would be great if you could provide one for me to test. Currently, I can only streamline the response schema
