### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by 1050TIt0p** [Lambdua/openai4j#26]
I use this API for a Discord bot with ChatGPT
After switching from the gpt-3.5-turbo model to the gpt-4o, sometimes an error started appearing during requests

Log:
https://pastes.dev/b0IFXKBXG1

**Comment by Lambdua** [comment]
You can set a longer timeout to test if the interface response is too slow. The default timeout event is 10 seconds
example:
```java
OpenAiService openAiService2 = new OpenAiService(API_KEY, Duration.ofSeconds(40));
```
