### ISSUE TITLE
streaming方式获取function call的argument

### ISSUE THREAD

**Issue by I-am-DJ** [Lambdua/openai4j#27]
执行测试用例时，对应messageChunk获取的arguments类型还是objectNode，导致解析为空
![image](https://github.com/Lambdua/openai4j/assets/33977935/ee23b15e-25b4-4477-aabc-3fee7c7a4f31)
我需要在初始化时做什么操作吗，设定不同的序列化方式？

**Comment by Lambdua** [comment]
你的例子我使用openai api 跑没有问题,你是用的第三方模型么

**Comment by I-am-DJ** [comment]
> 你的例子我使用openai api 跑没有问题,你是用的第三方模型么

我用的Qwen的模型

**Comment by Lambdua** [comment]
如果方便,你可以给我一个测试临时用的key 和对应的代码么. 发到我邮箱 lt547670718@gmail.com

**Comment by I-am-DJ** [comment]
> 如果方便,你可以给我一个测试临时用的key 和对应的代码么. 发到我邮箱 [lt547670718@gmail.com](mailto:lt547670718@gmail.com)

在公司的机器上搭建的，不太可行，可能是proxy层转发时候的问题，我排查下

**Comment by Lambdua** [comment]
国内三方代理proxy会有和官方接口不一致的行为. 如 [one-api](https://github.com/songquanpeng/one-api) ,我遇到过行为不一致的情况. 

我这边给你这种做个兼容处理,你稍后拉取代码本地编译测试下

**Comment by Lambdua** [comment]
@I-am-DJ 提交了,如果没问题,希望可以给一个star ,thanks.

**Comment by I-am-DJ** [comment]
看了你改的代码感觉并没有解决我这个问题

**Comment by I-am-DJ** [comment]
但是实际上他是有值的

> 看了你改的代码感觉并没有解决我这个问题， messageChunk.getFunctionCall().getArguments(); 我debug得到这行代码的类型是ObjectNode，他的asText()结果是空字符串

**Comment by Lambdua** [comment]
objectNode的情况是已经序列化完毕了. 这个是后续的argument我看你的debug是空.

**Comment by Lambdua** [comment]
你可以提交一个mq
