### ISSUE TITLE
parallel_tool_calls parameter support in Assistants and Chat Completions APIs

### ISSUE THREAD

**Issue by propertius** [Lambdua/openai4j#36]
Please add support for the new parameter `parallel_tool_calls` (see https://community.openai.com/t/new-api-feature-disable-parallel-function-calling-via-parallel-tool-calls-false/805405,  https://platform.openai.com/docs/api-reference/runs/createThreadAndRun and https://platform.openai.com/docs/api-reference/chat/create).

**Comment by Lambdua** [comment]
The latest version is currently supported, but some problems have occurred. It will be available in the next version soon after it is fixed.

**Comment by propertius** [comment]
Hi @Lambdua, I have the latest version of your library (0.20.9) and I cannot define whether tool calls are to be made parallel. The same applies for the ChatCompletionRequest.

```
var runRequest = RunCreateRequest.builder()
				.assistantId(assistantId)
				.parallelToolCalls(false) // not yet implemented
				.build();
```

**Comment by Lambdua** [comment]
0.21.0  will support
