### ISSUE TITLE
Do you need to switch to a higher version of JDK?

### ISSUE THREAD

**Issue by Lambdua** [Lambdua/openai4j#4]
I am the maintainer of this open-source library, and I developed it based on the openai Java library. Currently, the JDK 8 version is no longer suitable for my own needs. I have the idea of upgrading to a higher version of the JDK to use more of its features
However, this idea depends on the thoughts of the people using this library. I hope those who see this issue can provide their own opinions

**Comment by propertius** [comment]
I would try and keep supporting JDK 8. The 8 and 11 versions still dominate the production applications out there. Switching to 17 would seem too risky for me, and could eventually have an impact on this library's adoption. Here a poll from next year: https://www.jetbrains.com/lp/devecosystem-2023/java/

**Comment by Ran-Mewo** [comment]
If you want to try something experimental then you could have a look at [Jabel](https://github.com/bsideup/jabel)
It allows Java 9+ syntax when targeting for Java 8
