### ISSUE TITLE
Token统计可以计算文件搜索时使用的token数量吗

### ISSUE THREAD

**Issue by HappyDitto** [Lambdua/openai4j#40]
现有的token工具好像只能统计实际文字所使用的token，但搜索文件使用的token没有被统计。有什么办法统计搜索文件使用的token数量吗？

**Comment by Lambdua** [comment]
你是指使用assistant api的文件检索消耗的token么?

**Comment by HappyDitto** [comment]
> 你是指使用assistant api的文件检索消耗的token么?

对的

**Comment by Lambdua** [comment]
目前这个并不是透明的,官方好像并没有给出很透明的解析方案. [参考链接](https://community.openai.com/t/how-does-pricing-for-assistant-retrieval-work/637726/12)
assistant retrieval api 价格分为存储计费,和使用的对应模型tokens计费.
