### ISSUE TITLE
ImageContent from byte array or input stream

### ISSUE THREAD

**Issue by maximehamm** [Lambdua/openai4j#41]
I think there is no documentation about how to send Image from ByteArray or Stream... but I think the ChatGPT allow this ?  It is possible to send by url or "text"... what is a text image ??
Thank you for this great API !

**Comment by Lambdua** [comment]
ChatGPT is OpenAI's own ToC client.
The official API of OpenAi only supports link or image base64 encoding for image recognition dialogue. 
For base64 encoding, you can encode the image yourself and assign it to the imageUrl parameter
