### ISSUE TITLE
Support for max_num_results in FileSearchTool

### ISSUE THREAD

**Issue by ketanmpandya** [Lambdua/openai4j#42]
As of 0.21.0, it looks like the parameter max_num_results is not available in FileSearchTool. Is this on the roadmap?

See https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-tools (request body, under tools -> FileSearch)

**Comment by Lambdua** [comment]
I missed it, a new version will be released soon with the addition of

**Comment by ketanmpandya** [comment]
It looks like this parameter needs to be set in the payload for createRun, not createAssistant. (https://github.com/openai/openai-node/issues/886#issuecomment-2156257837)

Also, note that the parameter is supposed to be under "file_search" object in the tools JSON array. Like:

"tools": [
  {
    "type": "file_search",
    "file_search": {
      "max_num_results": 50
    }
  }
]

**Comment by Lambdua** [comment]
This parameter can also be used in CreatiAssistant, but the "file_dearch" object in my code was set incorrectly. Thank you for the reminder
