### ISSUE TITLE
Assistant Message and image_url

### ISSUE THREAD

**Issue by chrisetheridge** [Lambdua/openai4j#44]
When using this code: https://github.com/Lambdua/openai4j/blob/61fa82c77cf28653d0c5106c8a92def7d038388b/service/src/test/java/com/theokanning/openai/service/assistants/AssistantImageTest.java#L64-L87

The messages returned from `listMessages` don't have an ImageUrl object. They only have a `MessageContent` object with type `image_url` but no `image_url`. The Assistant Playground does show that this data is returned from the API when listing thread messages.

Is it possibly because the messages returned from the Threads API are being coerced to Assistant MessageContent which doesn't cater for `image_url`?

**Comment by chrisetheridge** [comment]
For example:

<img width="1086" alt="Screenshot 2024-06-26 at 20 45 34" src="https://github.com/Lambdua/openai4j/assets/11030306/b4dd877d-e162-4318-b419-ef8a961b9d05">

**Comment by Lambdua** [comment]
I'll take a look later. It may be a deserialization problem.

**Comment by chrisetheridge** [comment]
Thank you!

**Comment by Lambdua** [comment]
I haven't had time to look at it these past two days. It will be next week. If you are in a hurry, you can submit your mq to the specifications. Thank you.

**Comment by chrisetheridge** [comment]
No problem, no hurry.

Out of interest, can you explain 'mq to the specifications' a bit more? I'm not sure what that process is.
