### ISSUE TITLE
Type casting error occured when calling the Embedding Api using format by 'base64'

### ISSUE THREAD

**Issue by huyilong0516** [Lambdua/openai4j#5]
![image](https://github.com/Lambdua/openai4j/assets/13480783/7ebf7fd1-b9fc-4eee-9284-ba156a277ba9)

**Comment by xyifhgvnlo286** [comment]
你可以提供更多关于你的测试代码的内容吗,感谢

**Comment by Lambdua** [comment]
Received, will fix it tomorrow and plan to optimize the embedded API
