### ISSUE TITLE
报错 java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategies

### ISSUE THREAD

**Issue by kingxjs** [Lambdua/openai4j#6]
### service version
 **0.20.1**

```
<dependency>
  <groupId>io.github.lambdua</groupId>
  <artifactId>service</artifactId>
  <version>0.20.1</version>
</dependency>
```

异常信息：
```
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategies
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.theokanning.openai.service.OpenAiService.defaultObjectMapper(OpenAiService.java:180)
	at com.theokanning.openai.service.OpenAiService.<clinit>(OpenAiService.java:82)
	
```
![image](https://github.com/Lambdua/openai4j/assets/17718227/0f467df0-49cb-4f21-9ca5-1f78ddc23e88)

**Comment by huyilong0516** [comment]
检查Jackson版本是否过低
正确版本：
<dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.14.2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.14.2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.14.2</version>
            </dependency>

**Comment by kingxjs** [comment]
jackson version 2.11.2
不太好升级啊

**Comment by kingxjs** [comment]
0.19.1 还能用

**Comment by Lambdua** [comment]
下个版本我会优化一下,,这个配置不是必须的,我会去除.并优化一些OpenAiService的mapper配置. 代码已经提交了.如果你着急使用.自己编译 也行

**Comment by kingxjs** [comment]
多谢大佬

**Comment by Lambdua** [comment]
v0.20.4 已发布
