### ISSUE TITLE
Issues while switching over from TheoKanning/openai-java

### ISSUE THREAD

**Issue by anoopnarang** [Lambdua/openai4j#63]
We have been using [TheoKanning/openai-java](https://github.com/TheoKanning/openai-java) in our service. Since that is not being maintained anymore, we thought of switching over to this project.

One immediate issue we encountered was deprecation warning here https://github.com/Lambdua/openai4j/blob/8c4affc872ff0b9d454c445d0beddb6903983d6e/api/src/main/java/com/theokanning/openai/utils/TikTokensUtil.java#L18

What is the recommended alternative to `TikTokensUtil.java` ?
We want to count tokens before hand to make a decision whether to even make a request to open ai or not.

**Comment by Lambdua** [comment]
OpenAI now supports returning the token consumption amount at the end of the stream message, so there is no need to calculate it locally anymore

**Comment by Lambdua** [comment]
https://github.com/Lambdua/openai4j/blob/5d23368d9431c7c3d08423190fe684c9672437a2/api/src/main/java/com/theokanning/openai/completion/chat/StreamOption.java#L17
You can use this configuration item when creating requests, and then you can view usage usage afterwards
