### ISSUE TITLE
jackson必须要升级到2.14.2吗？

### ISSUE THREAD

**Issue by kingxjs** [Lambdua/openai4j#67]
刚更新最新版本 v0.22.2，报异常 JacksonException 不存在，是必须更新jackson版本吗？

**Comment by Lambdua** [comment]
main分支最新提交，去除了JacksonException 的使用，你可以自己clone mvn package 试下能否使用呢。  暂时不会更新新版本（没有重大bug)

**Comment by kingxjs** [comment]
感谢！
