### ISSUE TITLE
 Embedding Api lack of utils for 'cosine_similarity' method, did you have any plan to complete it?

### ISSUE THREAD

**Issue by huyilong0516** [Lambdua/openai4j#7]
Such as official Doc giving :
![image](https://github.com/Lambdua/openai4j/assets/13480783/36f32cd4-44fe-4679-bedd-3628f4fd0db7)
it is available in py sdk.

**Comment by Lambdua** [comment]
Let me take a look first. If you can provide PR, that would be great

**Comment by Lambdua** [comment]
我看了下,这不属于openAi api的范围之内。而且也有支持的java库计算余弦相似度.例如Apache Commons Math。.你可以参考然后自己使用

**Comment by huyilong0516** [comment]
好的，我去找下Apache Commons Math 这个库
