### ISSUE TITLE
Support for the required field on the ResponseJsonSchema class

### ISSUE THREAD

**Issue by winfredekpe** [Lambdua/openai4j#79]
![Screenshot 2024-12-02 143900](https://github.com/user-attachments/assets/7a588db8-bbba-480a-8567-4c122f6981f8)

![image](https://github.com/user-attachments/assets/72db4c58-afb3-4fdb-9bb4-a0e52f4b37e6)

**Comment by winfredekpe** [comment]
`java 

package org.example;

import com.theokanning.openai.completion.chat.*;
import com.theokanning.openai.service.OpenAiService;

import java.util.ArrayList;
import java.util.List;


class Response {


    String brands;
    String side_effects;

    public String getBrands() {
        return brands;
    }

    public void setBrands(String brands) {
        this.brands = brands;
    }

    public String getSide_effects() {
        return side_effects;
    }

    public void setSide_effects(String side_effects) {
        this.side_effects = side_effects;
    }


}


/**
 *
 */
public class app {


    public static void main(String[] args) {


        String apiKey = "your key here";


        OpenAiService service = new OpenAiService(apiKey);


//        message
        List<ChatMessage> messages = new ArrayList<>();
        ChatMessage systemMessage = new SystemMessage("give me the brands and side effects of painkillers");
        messages.add(systemMessage);


//        format
        ResponseJsonSchema ResponseJsonSchema = new ResponseJsonSchema();
        ResponseJsonSchema.setName("painkillers");
        ResponseJsonSchema.setSchemaClass(Response.class);
        ResponseJsonSchema.setStrict(true);


//        request
        ChatCompletionRequest chatCompletionRequest = ChatCompletionRequest.builder()
                .model("gpt-4o-mini")
                .messages(messages).responseFormat(ChatResponseFormat.jsonSchema(ResponseJsonSchema))
                .maxTokens(50)
                .build();


//        result processing
        ChatCompletionResult chatCompletion = service.createChatCompletion(chatCompletionRequest);
        System.out.println(chatCompletion.getChoices().get(0).getMessage().getContent());


    }


}






`

**Comment by Lambdua** [comment]
```java

class Response {
@NotNull
String brands;
@NotNull
String side_effects;
...
}
```



After you add the annotation `@NotNull`, the `JsonSchemaGenerator` class will be added

```json

"required": [
    "brands",
    "side_effects"
]
```

Regarding the serialization of jsonScheme, I used `mbknor-jackson-jsonschema_2.12` to implement it.
Below is the relevant OpenAI documentation; https://openai.com/index/introducing-structured-outputs-in-the-api/
