### ISSUE TITLE
文件上传是否能支持字节流传输？

### ISSUE THREAD

**Issue by huyilong0516** [Lambdua/openai4j#8]
![image](https://github.com/Lambdua/openai4j/assets/13480783/52905bba-db24-45af-a3f1-338fd12417b2)
我看现在文件只支持了路径上传，如果字节流的话，现在有方法可以支持吗？

**Comment by Lambdua** [comment]
下版本更新支持 #

**Comment by Lambdua** [comment]
support by v0.20.4
