### ISSUE TITLE
Message List 查询，缺少参数 [run_id]

### ISSUE THREAD

**Issue by huyilong0516** [Lambdua/openai4j#9]
![image](https://github.com/Lambdua/openai4j/assets/13480783/dc339615-dd10-4a58-a833-91912e745b11)
![image](https://github.com/Lambdua/openai4j/assets/13480783/4bb5b788-642c-414a-ad5f-ca4c2d7c2d57)

**Comment by Lambdua** [comment]
ok

**Comment by Lambdua** [comment]
fixed by v0.20.4
